package com.local.yongsanimaxwatcher;

import android.Manifest; import android.app.*; import android.content.*; import android.content.pm.PackageManager; import android.graphics.*; import android.graphics.drawable.GradientDrawable; import android.net.Uri; import android.os.*; import android.provider.Settings; import android.text.InputType; import android.view.*; import android.widget.*;
import java.time.LocalDate; import java.time.format.DateTimeFormatter; import java.util.*; import java.util.concurrent.*;

public final class MainActivity extends Activity {
 private static final int RED=Color.rgb(232,32,48), BG=Color.rgb(247,247,247), TEXT=Color.rgb(25,25,25), SUB=Color.rgb(105,105,105), BORDER=Color.rgb(225,225,225);
 private final String[][] THEATERS={{"용산아이파크몰","0013"},{"왕십리","0074"},{"영등포","0059"},{"강남","0056"},{"여의도","0112"},{"신촌아트레온","0150"},{"홍대","0191"},{"건대입구","0229"},{"동대문","0252"},{"천호","0199"},{"압구정","0040"},{"청담씨네시티","0107"},{"구로","0010"},{"상봉","0046"},{"중계","0131"},{"직접 입력",""}};
 private Prefs prefs; private KakaoClient kakao; private final Handler ui=new Handler(Looper.getMainLooper()); private final ExecutorService loader=Executors.newSingleThreadExecutor();
 private Spinner theaterSpinner; private LinearLayout dateRow,movieList; private TextView statusPill,statusDetail,selectedCount,selectedPreview,emptyHint; private Button refreshButton,startStop; private final Map<String,List<CgvClient.Showtime>> showsByDate=new LinkedHashMap<>(); private String currentDate=""; private boolean loading=false;
 private final Runnable refresher=new Runnable(){public void run(){refreshStatus();ui.postDelayed(this,1500);}};
 public void onCreate(Bundle b){super.onCreate(b);prefs=new Prefs(this);kakao=new KakaoClient(this);new NotificationHelper(this);requestNotificationPermission();setContentView(buildUi());ui.post(refresher);ui.postDelayed(()->loadSchedule(false),250);}
 private View buildUi(){LinearLayout page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setBackgroundColor(BG);page.addView(buildHeader());ScrollView scroll=new ScrollView(this);LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(110));c.addView(buildWatchCard());c.addView(sectionTitle("1  극장 선택"),top(20));c.addView(buildTheaterSelector(),top(8));c.addView(sectionTitle("2  날짜 선택"),top(22));dateRow=new LinearLayout(this);dateRow.setOrientation(LinearLayout.HORIZONTAL);HorizontalScrollView ds=new HorizontalScrollView(this);ds.setHorizontalScrollBarEnabled(false);ds.addView(dateRow);c.addView(ds,top(8));LinearLayout mh=new LinearLayout(this);mh.setGravity(Gravity.CENTER_VERTICAL);mh.addView(sectionTitle("3  영화와 알림 선택"),new LinearLayout.LayoutParams(0,-2,1));refreshButton=smallButton("새로고침");refreshButton.setOnClickListener(v->loadSchedule(true));mh.addView(refreshButton);c.addView(mh,top(22));TextView guide=text("🔔 영화 옆 버튼 = 새 날짜 오픈 알림\n🎟 시간 버튼 = 그 회차 취소표 알림",14,true,TEXT);guide.setPadding(dp(12),dp(12),dp(12),dp(12));guide.setBackground(roundBg(Color.WHITE,dp(12),BORDER,1));c.addView(guide,top(8));emptyHint=text("시간표 불러오는 중…",14,false,SUB);c.addView(emptyHint,top(10));movieList=new LinearLayout(this);movieList.setOrientation(LinearLayout.VERTICAL);c.addView(movieList);scroll.addView(c);page.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));page.addView(buildBottomBar());return page;}
 private View buildHeader(){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(18),dp(14),dp(8),dp(14));h.setBackgroundColor(Color.WHITE);h.addView(text("CGV WATCH",22,true,RED),new LinearLayout.LayoutParams(0,-2,1));Button o=flatButton("CGV 열기");o.setOnClickListener(v->openCgv());h.addView(o);Button s=flatButton("설정");s.setOnClickListener(v->showSettings());h.addView(s);return h;}
 private View buildWatchCard(){LinearLayout card=card();LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);r.addView(text("내 알림",18,true,TEXT),new LinearLayout.LayoutParams(0,-2,1));statusPill=text("정지",12,true,SUB);statusPill.setPadding(dp(10),dp(5),dp(10),dp(5));r.addView(statusPill);card.addView(r);selectedCount=text("",22,true,TEXT);card.addView(selectedCount,top(12));selectedPreview=text("",13,false,SUB);selectedPreview.setLineSpacing(dp(2),1);card.addView(selectedPreview,top(7));statusDetail=text("",12,false,SUB);card.addView(statusDetail,top(10));return card;}
 private View buildTheaterSelector(){LinearLayout card=card();theaterSpinner=new Spinner(this);ArrayList<String> n=new ArrayList<>();int sel=0;for(int i=0;i<THEATERS.length;i++){n.add("CGV "+THEATERS[i][0]);if(THEATERS[i][1].equals(prefs.getSiteNo()))sel=i;}theaterSpinner.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,n));theaterSpinner.setSelection(sel);theaterSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){boolean first=true;public void onItemSelected(android.widget.AdapterView<?>p,View v,int pos,long id){if(first){first=false;return;}if(pos==THEATERS.length-1){showCustomTheaterDialog();return;}applyTheater(THEATERS[pos][0],THEATERS[pos][1]);}public void onNothingSelected(android.widget.AdapterView<?>p){}});card.addView(theaterSpinner);return card;}
 private View buildBottomBar(){LinearLayout b=new LinearLayout(this);b.setPadding(dp(16),dp(10),dp(16),dp(14));b.setBackgroundColor(Color.WHITE);Button clear=outlinedButton("전체 해제");clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("모든 알림 선택을 해제할까?").setMessage("새 날짜 알림과 취소표 알림을 모두 해제해.").setPositiveButton("해제",(d,w)->{prefs.clearSelectedShowtimes();prefs.clearNewDateMovies();prefs.resetBaseline();renderMovies();refreshStatus();}).setNegativeButton("취소",null).show());b.addView(clear,new LinearLayout.LayoutParams(dp(104),dp(54)));startStop=redButton("감시 시작");startStop.setOnClickListener(v->toggleWatch());LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(54),1);lp.leftMargin=dp(10);b.addView(startStop,lp);return b;}
 private void applyTheater(String n,String s){if(s.equals(prefs.getSiteNo())&&n.equals(prefs.getTheaterName()))return;if(prefs.isWatching())stopWatchService();prefs.setTarget(n,s,"","");showsByDate.clear();currentDate="";loadSchedule(false);}
 private void showCustomTheaterDialog(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(20),0,dp(20),0);EditText n=input("극장명",false),c=input("극장 코드 4자리",false);c.setInputType(InputType.TYPE_CLASS_NUMBER);b.addView(n);b.addView(c);new AlertDialog.Builder(this).setTitle("CGV 직접 입력").setView(b).setPositiveButton("적용",(d,w)->{String nn=n.getText().toString().trim(),cc=c.getText().toString().trim();if(nn.isEmpty()||!cc.matches("\\d{4}")){toast("극장명과 4자리 코드를 확인해줘.");return;}applyTheater(nn,cc);}).setNegativeButton("취소",null).show();}
 private void loadSchedule(boolean manual){if(loading)return;loading=true;refreshButtonSafe(false,"불러오는 중…");movieList.removeAllViews();emptyHint.setVisibility(View.VISIBLE);emptyHint.setText("CGV 영화/시간표 불러오는 중…");String tn=prefs.getTheaterName(),sn=prefs.getSiteNo();loader.execute(()->{Map<String,List<CgvClient.Showtime>> r=new LinkedHashMap<>();Exception last=null;CgvClient client=new CgvClient(tn,sn,"","");LocalDate today=DateUtil.today();for(int i=0;i<8;i++){String d=DateUtil.ymd(today.plusDays(i));try{r.put(d,dedupe(client.fetchMatches(d)));}catch(Exception e){last=e;r.put(d,new ArrayList<>());}try{Thread.sleep(160);}catch(Exception ignored){}}Exception err=last;runOnUiThread(()->{loading=false;refreshButtonSafe(true,"새로고침");showsByDate.clear();showsByDate.putAll(r);if(currentDate.isEmpty()||!showsByDate.containsKey(currentDate)){currentDate=firstDateWithShows(r);if(currentDate.isEmpty())currentDate=DateUtil.ymd(DateUtil.today());}renderDates();renderMovies();if(allEmpty(r)){emptyHint.setVisibility(View.VISIBLE);emptyHint.setText(err==null?"상영시간이 없어.":"시간표를 못 불러왔어.\n"+clean(err.getMessage()));}else if(manual)toast("최신 시간표로 갱신했어.");});});}
 private List<CgvClient.Showtime> dedupe(List<CgvClient.Showtime>s){LinkedHashMap<String,CgvClient.Showtime>m=new LinkedHashMap<>();for(CgvClient.Showtime x:s)m.put(x.key(),x);ArrayList<CgvClient.Showtime>o=new ArrayList<>(m.values());Collections.sort(o,Comparator.comparing((CgvClient.Showtime x)->x.title).thenComparing(x->x.time));return o;}
 private void renderDates(){dateRow.removeAllViews();LocalDate today=DateUtil.today();DateTimeFormatter day=DateTimeFormatter.ofPattern("M/d",Locale.KOREA),dow=DateTimeFormatter.ofPattern("E",Locale.KOREA);for(int i=0;i<8;i++){LocalDate d=today.plusDays(i);String k=DateUtil.ymd(d);boolean a=k.equals(currentDate);TextView chip=text((i==0?"오늘\n":dow.format(d)+"\n")+day.format(d),13,a,a?Color.WHITE:TEXT);chip.setGravity(Gravity.CENTER);chip.setBackground(roundBg(a?RED:Color.WHITE,dp(14),a?RED:BORDER,1));chip.setOnClickListener(v->{currentDate=k;renderDates();renderMovies();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(66),dp(62));lp.rightMargin=dp(8);dateRow.addView(chip,lp);}}
 private void renderMovies(){movieList.removeAllViews();List<CgvClient.Showtime>l=showsByDate.get(currentDate);if(l==null||l.isEmpty()){emptyHint.setVisibility(View.VISIBLE);emptyHint.setText("이 날짜에는 상영 회차가 없어.");return;}emptyHint.setVisibility(View.GONE);LinkedHashMap<String,List<CgvClient.Showtime>>m=new LinkedHashMap<>();for(CgvClient.Showtime s:l)m.computeIfAbsent(s.title,k->new ArrayList<>()).add(s);for(Map.Entry<String,List<CgvClient.Showtime>>e:m.entrySet())movieList.addView(movieCard(e.getKey(),e.getValue()),top(10));}
 private View movieCard(String title,List<CgvClient.Showtime>shows){LinearLayout card=card();LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(text(title,18,true,TEXT),new LinearLayout.LayoutParams(0,-2,1));boolean dateOn=prefs.isNewDateMovie(title);Button bell=smallButton(dateOn?"🔔 새 날짜 ON":"🔕 새 날짜 알림");bell.setTextColor(dateOn?Color.WHITE:TEXT);bell.setBackground(roundBg(dateOn?RED:Color.WHITE,dp(12),dateOn?RED:BORDER,1));bell.setOnClickListener(v->{prefs.toggleNewDateMovie(title);renderMovies();refreshStatus();});head.addView(bell);card.addView(head);card.addView(text("아래 시간은 취소표 알림을 받을 회차만 선택",12,false,SUB),top(7));LinearLayout times=new LinearLayout(this);times.setOrientation(LinearLayout.VERTICAL);card.addView(times,top(9));int i=0;while(i<shows.size()){LinearLayout row=new LinearLayout(this);for(int col=0;col<3;col++){if(i>=shows.size()){View sp=new View(this);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(1),1);row.addView(sp,p);continue;}CgvClient.Showtime s=shows.get(i++);boolean on=prefs.getSelectedShowtimeKeys().contains(s.key());TextView btn=showtimeButton(s,on);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(60),1);if(col>0)p.leftMargin=dp(7);row.addView(btn,p);}times.addView(row,times.getChildCount()==0?new LinearLayout.LayoutParams(-1,-2):top(7));}return card;}
 private TextView showtimeButton(CgvClient.Showtime s,boolean on){String seats=s.freeSeats>=0?"\n"+s.freeSeats+"석":"";TextView b=text((on?"✓ ":"")+s.time+seats,14,true,on?Color.WHITE:TEXT);b.setGravity(Gravity.CENTER);b.setBackground(roundBg(on?RED:Color.WHITE,dp(10),on?RED:BORDER,1));b.setOnClickListener(v->toggleShowtime(s));return b;}
 private void toggleShowtime(CgvClient.Showtime s){Set<String>k=prefs.getSelectedShowtimeKeys(),l=prefs.getSelectedShowtimeLabels();String label=DateUtil.pretty(s.date)+" · "+s.title+" · "+s.time;if(k.contains(s.key())){k.remove(s.key());l.remove(label);}else{k.add(s.key());l.add(label);}prefs.setSelectedShowtimes(k,l);renderMovies();refreshStatus();}
 private void toggleWatch(){if(prefs.isWatching()){stopWatchService();return;}if(!prefs.hasAnyWatch()){new AlertDialog.Builder(this).setTitle("알림을 하나 이상 선택해줘").setMessage("영화의 🔔 새 날짜 알림을 켜거나, 원하는 상영시간을 눌러 취소표 알림을 선택해.").setPositiveButton("확인",null).show();return;}if(!kakao.hasRefreshToken())new AlertDialog.Builder(this).setTitle("카카오 미연결").setMessage("폰 알림은 정상적으로 받을 수 있어. 시작할까?").setPositiveButton("시작",(d,w)->startWatchService()).setNegativeButton("취소",null).show();else startWatchService();}
 private void startWatchService(){Intent i=new Intent(this,WatchService.class);i.setAction(WatchService.ACTION_START);startForegroundService(i);prefs.setWatching(true);refreshStatus();toast("감시 시작했어.");} private void stopWatchService(){Intent i=new Intent(this,WatchService.class);i.setAction(WatchService.ACTION_STOP);startService(i);prefs.setWatching(false);refreshStatus();}
 private void refreshStatus(){if(statusPill==null)return;boolean w=prefs.isWatching();statusPill.setText(w?"● 감시 중":"정지");statusPill.setTextColor(w?Color.WHITE:SUB);statusPill.setBackground(roundBg(w?RED:Color.rgb(238,238,238),dp(20),Color.TRANSPARENT,0));int nd=prefs.getNewDateMovies().size(),st=prefs.getSelectedShowtimeKeys().size();selectedCount.setText("🔔 새 날짜 "+nd+"   ·   🎟 취소표 "+st);selectedPreview.setText(selectionPreview());statusDetail.setText("마지막 확인 "+prefs.getLastChecked()+"  ·  "+prefs.getIntervalSeconds()+"초 간격"+(kakao.hasRefreshToken()?"  ·  카카오 연결":""));startStop.setText(w?"감시 중지":"감시 시작");startStop.setBackground(roundBg(w?Color.rgb(50,50,50):RED,dp(13),Color.TRANSPARENT,0));}
 private String selectionPreview(){StringBuilder b=new StringBuilder();Set<String>movies=prefs.getNewDateMovies();if(!movies.isEmpty())b.append("📅 새 날짜: ").append(android.text.TextUtils.join(", ",movies));ArrayList<String>labels=new ArrayList<>(prefs.getSelectedShowtimeLabels());Collections.sort(labels);if(!labels.isEmpty()){if(b.length()>0)b.append("\n");b.append("🎟 취소표: ");for(int i=0;i<Math.min(3,labels.size());i++){if(i>0)b.append("\n          ");b.append(labels.get(i));}if(labels.size()>3)b.append(" 외 ").append(labels.size()-3).append("개");}if(b.length()==0)return "영화의 🔔 또는 원하는 시간을 눌러 알림을 선택해.";return b.toString();}
 private void showSettings(){LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(20),0,dp(20),0);b.addView(text("카카오 알림",16,true,TEXT));EditText rest=input("Kakao REST API 키",false),secret=input("Kakao Client Secret",true);rest.setText(kakao.getRestKey());secret.setText(kakao.getClientSecret());b.addView(rest);b.addView(secret);LinearLayout kb=new LinearLayout(this);Button login=outlinedButton(kakao.hasRefreshToken()?"카카오 재로그인":"카카오 로그인"),test=outlinedButton("테스트");kb.addView(login,new LinearLayout.LayoutParams(0,dp(48),1));kb.addView(test,new LinearLayout.LayoutParams(0,dp(48),1));b.addView(kb);b.addView(text("감시 간격",16,true,TEXT),top(14));Spinner interval=new Spinner(this);interval.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"30초","1분","2분"}));interval.setSelection(prefs.getIntervalSeconds()==120?2:prefs.getIntervalSeconds()==60?1:0);b.addView(interval);CheckBox auto=new CheckBox(this);auto.setText("재부팅 후 자동 감시 재시작");auto.setChecked(prefs.isAutoRestart());b.addView(auto);AlertDialog d=new AlertDialog.Builder(this).setTitle("설정").setView(b).setPositiveButton("저장",null).setNegativeButton("닫기",null).create();d.setOnShowListener(x->{login.setOnClickListener(v->{kakao.saveAppKeys(rest.getText().toString(),secret.getText().toString());kakao.login(this,(ok,msg)->runOnUiThread(()->showResult(ok?"카카오 연결 완료":"카카오 연결 실패",msg)));});test.setOnClickListener(v->{kakao.saveAppKeys(rest.getText().toString(),secret.getText().toString());kakao.sendTestAsync(this,(ok,msg)->runOnUiThread(()->showResult(ok?"테스트 성공":"테스트 실패",msg)));});d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{kakao.saveAppKeys(rest.getText().toString(),secret.getText().toString());prefs.setIntervalSeconds(interval.getSelectedItemPosition()==2?120:interval.getSelectedItemPosition()==1?60:30);prefs.setAutoRestart(auto.isChecked());refreshStatus();d.dismiss();});});d.show();}
 private void openCgv(){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(CgvClient.bookingUrl(prefs.getTheaterName(),prefs.getSiteNo()))));}
 private String firstDateWithShows(Map<String,List<CgvClient.Showtime>>d){for(Map.Entry<String,List<CgvClient.Showtime>>e:d.entrySet())if(e.getValue()!=null&&!e.getValue().isEmpty())return e.getKey();return "";} private boolean allEmpty(Map<String,List<CgvClient.Showtime>>d){for(List<CgvClient.Showtime>l:d.values())if(l!=null&&!l.isEmpty())return false;return true;}
 private LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),dp(15),dp(16),dp(15));l.setBackground(roundBg(Color.WHITE,dp(16),BORDER,1));return l;} private TextView sectionTitle(String s){return text(s,17,true,TEXT);} private TextView text(String s,int z,boolean bold,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return t;}
 private Button redButton(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(16);b.setAllCaps(false);b.setBackground(roundBg(RED,dp(13),Color.TRANSPARENT,0));return b;} private Button outlinedButton(String s){Button b=new Button(this);b.setText(s);b.setTextColor(TEXT);b.setAllCaps(false);b.setBackground(roundBg(Color.WHITE,dp(12),BORDER,1));return b;} private Button smallButton(String s){Button b=outlinedButton(s);b.setMinHeight(0);b.setMinimumHeight(0);b.setPadding(dp(10),dp(5),dp(10),dp(5));return b;} private Button flatButton(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setBackgroundColor(Color.TRANSPARENT);return b;}
 private EditText input(String h,boolean pass){EditText e=new EditText(this);e.setHint(h);e.setSingleLine(true);if(pass)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);return e;} private GradientDrawable roundBg(int f,int r,int st,int sw){GradientDrawable g=new GradientDrawable();g.setColor(f);g.setCornerRadius(r);if(sw>0)g.setStroke(dp(sw),st);return g;} private LinearLayout.LayoutParams top(int x){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=dp(x);return p;} private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);} private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();} private void refreshButtonSafe(boolean e,String s){if(refreshButton!=null){refreshButton.setEnabled(e);refreshButton.setText(s);}} private void showResult(String t,String m){new AlertDialog.Builder(this).setTitle(t).setMessage(m).setPositiveButton("확인",null).show();refreshStatus();} private static String clean(String s){return s==null?"오류":s.replace("\n"," ");}
 private void requestNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},100);} public void onDestroy(){ui.removeCallbacks(refresher);loader.shutdownNow();super.onDestroy();}
}
